spring:
  application:
    name: Biblioteca API
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console

